### ISSUE TITLE
已经安装SQLite for BungeeCord，但依然。。。

### ISSUE THREAD

**Issue by SnowSwordScholar** [lintx/Minecraft-Plugin-WebAuth#4]
> webauth reload
[02:35:14 ERROR]: java.lang.IllegalArgumentException: No enum constant org.lintx.plugin.webauth.config.DatabaseConfig.DatabaseType.SQLite
[02:35:14 ERROR]:       at java.base/java.lang.Enum.valueOf(Enum.java:240)
[02:35:14 ERROR]:       at org.lintx.plugins.webauth.maven.modules.configure.BungeeConfigure.deserialize(BungeeConfigure.java:177)
[02:35:14 ERROR]:       at org.lintx.plugins.webauth.maven.modules.configure.BungeeConfigure.deserialize(BungeeConfigure.java:190)
[02:35:14 ERROR]:       at org.lintx.plugins.webauth.maven.modules.configure.BungeeConfigure.load(BungeeConfigure.java:70)
[02:35:14 ERROR]:       at org.lintx.plugins.webauth.maven.modules.configure.Configure.bungeeLoad(Configure.java:14)
[02:35:14 ERROR]:       at org.lintx.plugins.webauth.maven.modules.configure.Configure.bungeeLoad(Configure.java:10)
[02:35:14 ERROR]:       at org.lintx.plugin.webauth.Config.load(Config.java:20)
[02:35:14 ERROR]:       at org.lintx.plugin.webauth.WebAuth.reload(WebAuth.java:117)
[02:35:14 ERROR]:       at org.lintx.plugin.webauth.Commands.execute(Commands.java:162)
[02:35:14 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
[02:35:14 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
[02:35:14 ERROR]:       at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
[02:35:14 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
[02:35:14 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168)
[02:35:14 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[02:35:14 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
[02:35:14 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[02:35:24 INFO]: 重新加载配置文件

**Comment by SnowSwordScholar** [comment]
好吧，大小写错了。。。
